### ISSUE TITLE
[REVIEW] [BUG 53] Forwarding after successfully signing in (this was reported by a community member via Slack)

### ISSUE THREAD

**Issue by dimakrsna** [butterfyme/Sparkable#183]
https://www.notion.so/sparkable/53-Forwarding-after-successfully-signing-in-this-was-reported-by-a-community-member-via-Slack-fc034192777d4a32be2e6f0fc13a65b2?pvs=4

**Comment by hynnot** [comment]
**Intention (What did you want to do?)**

They wanted to sign in: 
They entered their username and password with a password manager, and the “Successful sign in” message appeared. 

OS: Android; Browser: Chrome; I asked them to delete the cache but they said that they hadn’t accessed [sparkable.cc](http://sparkable.cc/) before because the phone was new.

**What happened?**

After the success message they were forwarded to the Create Account screen. When they clicked on the Sparkable home link, they were signed in.

**What did you expect?**

They expected to be forwarded to the Start page, and not to the Create Account screen.
